config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :properties do
    resources :units
  end

  root 'search#index'

  get :search, to: 'search#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  has_many :units, dependent: :destroy
end

app/models/unit.rb
# frozen_string_literal: true

class Unit < ApplicationRecord
  belongs_to :property
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]

  # GET /properties
  def index
    @pagy, @properties = pagy(Property.all.includes(:units))
  end

  # GET /properties/1
  def show; end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit; end

  # POST /properties
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  def destroy
    @property.destroy!

    respond_to do |format|
      format.html { redirect_to properties_path, status: :see_other, notice: 'Property was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.expect(property: %i[address city state])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  # GET /properties
  def index
    @pagy, @properties = pagy(find_properties)
  end

  private

  def find_properties
    property_search_params = permitted_search_params

    SearchProperties.call(property_search_params)
  end

  def permitted_search_params
    params.permit(:query)
  end
end

app/controllers/units_controller.rb
# frozen_string_literal: true

class UnitsController < ApplicationController
  before_action :set_property
  before_action :set_unit, only: %i[show edit update destroy]

  # GET /units
  def index
    @units = Unit.all
  end

  # GET /units/1
  def show; end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit; end

  # POST /units
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to [@property, @unit], notice: 'Unit was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to [@property, @unit], notice: 'Unit was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy!

    respond_to do |format|
      format.html do
        redirect_to property_units_path(@property), status: :see_other, notice: 'Unit was successfully destroyed.'
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params.expect(:property_id))
  end

  def set_unit
    @unit = Unit.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def unit_params
    params.expect(unit: %i[bedroom_count bathroom_count square_footage
                           rent_price]).merge(property_id: @property.id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/properties_helper.rb
# frozen_string_literal: true

module PropertiesHelper
end

app/helpers/units_helper.rb
# frozen_string_literal: true

module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rentasearch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-6 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/properties/_empty.html.erb
<tr><td colspan="3">No properties currently.</td></tr>

app/views/properties/_form.html.erb
<%= form_with(model: property, class: "contents") do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<tr id="<%= dom_id property %>" class="odd:bg-slate-50 even:bg-white">
  <td class="py-5">
    <%= property.address %>
    <%= property.city %>
    <%= property.state %>
  </td>
  <td class="py-5 text-center">
  <%= link_to pluralize(property.units.count, 'Unit'),
    property_units_path(property),
    class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </td>
  <td>
    <%= link_to "Edit", 
      edit_property_path(property),
      class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= button_to "Destroy", 
      property, 
      method: :delete, 
      class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium", 
      data: { 
        turbo_method: :delete, 
        turbo_confirm: "Are you sure you want to delete this property?" } %>
  </td>
</tr>

app/views/properties/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing property</h1>

  <%= render "form", property: @property %>

  <%= link_to "Show this property", @property, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to properties", properties_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/properties/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Properties" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Properties</h1>
    <%= link_to "New property", new_property_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="properties" class="min-w-full">
    <table class="w-full">
      <thead>
        <tr>
          <th>Address</th>
          <th>Units</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render(@properties) || render('empty') %>
      </tbody>
    </table>
  </div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/properties/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New property</h1>

  <%= render "form", property: @property %>

  <%= link_to "Back to properties", properties_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/properties/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @property %>

    <%= link_to "Edit this property", edit_property_path(@property), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to properties", properties_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this property", @property, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/search/_empty.html.erb
No properties currently.

app/views/search/_result.html.erb
<div id="<%= dom_id result %>" class="odd:bg-slate-50 even:bg-white">
  <p class="min-w-full p-5">
    <%= result.address %>
    <%= result.city %>
    <%= result.state %>
  </p>
  <% if result.units.present? %>
    <table class="mt-5 p-5">
      <thead>
        <tr>
          <th class="px-5">bedroom count</th>
          <th class="px-5">bathroom count</th>
          <th class="px-5">rent price</th>
        </tr>
      </thead>
      <tbody>
        <% result.units.each do |unit| %>
          <tr class="odd:bg-stone-100 even:bg-stone-50">
            <td class="text-center"><%= unit.bedroom_count %></td>
            <td class="text-center"><%= unit.bathroom_count %></td>
            <td class="text-center"><%= unit.bedroom_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/search/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Search" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Search</h1>
      <%= form_with(url: search_url, method: 'get', local: true) do %>
    <div>
      <%= text_field_tag(:query, nil, { autocomplete: :off, class: 'border' } ) %>
      <%= submit_tag('Search', name: nil) %>
    </div>
  <% end %>
  </div>

  <div id="properties" class="min-w-full my-5">
    <%= render partial: "result", collection: @properties || render('empty') %>
  </div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/units/_form.html.erb
<%= form_with(model: [@property, unit], class: "contents") do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :bedroom_count %>
    <%= form.number_field :bedroom_count, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bathroom_count %>
    <%= form.number_field :bathroom_count, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :square_footage %>
    <%= form.number_field :square_footage, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rent_price %>
    <%= form.number_field :rent_price, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Property:</strong>
    <%= unit.property_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bedroom count:</strong>
    <%= unit.bedroom_count %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bathroom count:</strong>
    <%= unit.bathroom_count %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Square footage:</strong>
    <%= unit.square_footage %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rent price:</strong>
    <%= unit.rent_price %>
  </p>

</div>

app/views/units/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing unit</h1>

  <%= render "form", unit: @unit %>

  <%= link_to "Show this unit", @unit, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to units", property_units_path(@property), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/units/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Units" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Units</h1>
    <%= link_to "New unit", new_property_unit_path(@property), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="units" class="min-w-full">
    <% @units.each do |unit| %>
      <%= render unit %>
      <p>
        <%= link_to "Show this unit", [@property, unit], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/units/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New unit</h1>

  <%= render "form", unit: @unit %>

  <%= link_to "Back to units", property_units_path(@property), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/units/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @unit %>

    <%= link_to "Edit this unit", edit_property_unit_path(@property, @unit), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to units", property_units_path(@property), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this unit", [@property, @unit], method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>